// <auto-generated />
using CitiesInfoWeb.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesInfoWeb.Migrations
{
    [DbContext(typeof(CitiesInfoWebContext))]
    partial class CitiesInfoWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("CitiesInfoWeb.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The most famous USA's city",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The capital of the Great Britain",
                            Name = "London"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Is not the capital of Australia",
                            Name = "Sydney"
                        });
                });

            modelBuilder.Entity("CitiesInfoWeb.Entities.PointsOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "It's Times Square",
                            Name = "Times Square"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "It's Central Park",
                            Name = "Central Park"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "London Eye",
                            Name = "London Eye"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "It's Big Ben",
                            Name = "Big Ben"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "It's Opera House",
                            Name = "Opera House"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "It's Tarong Zoo",
                            Name = "Tarong Zoo"
                        });
                });

            modelBuilder.Entity("CitiesInfoWeb.Entities.PointsOfInterest", b =>
                {
                    b.HasOne("CitiesInfoWeb.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CitiesInfoWeb.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
